[package]
name = "project-x-generator"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
project-x-metadata = { version = "0.1.0", path = "../metadata" }
quote = "1.0.9"
syn = "1.0.73"
convert_case = "0.4.0"
