[package]
name = "gekko-metadata"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
parity-scale-codec = { version = "2.2.0", features = ["derive"] }
hex = "0.4.3"
